name: aa_prompt_ui
description: "A Flutter UI for apparmor prompting."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  yaru:
    git:
      url: https://github.com/ubuntu/yaru.dart.git
      ref: main
  yaru_widgets: ^1.1.2
  ubuntu_lints: ^0.3.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_serializable: ^6.8.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
