name: prompting-client
base: core22
version: '0.1'
summary: A client for snapd apparmor prompting
description: |
  The official client for snap apparmor prompting.
grade: devel
confinement: strict

apps:
  prompting-client:
    command: bin/prompting-client-cli
    extensions: [gnome]
    environment: &env
      PROMPTING_CLIENT_SOCKET: "${XDG_RUNTIME_DIR}/prompting.sock"
    plugs: &plugs
      - home
      - snap-prompting-control

  daemon:
    command: bin/prompting-client-daemon
    extensions: [gnome]
    environment: *env
    plugs: *plugs
    daemon: simple
    passthrough: # TODO: Remove once daemon-scope lands in snapcraft
      daemon-scope: user
    restart-condition: on-success
    restart-delay: 2s

parts:
  flutter-git:
    plugin: nil
    source: .
    override-pull: |
      # necessary when reruns using the same container
      if [ -d "flutter" ]; then
        rm -rf "flutter"
      fi

      craftctl default
      FLUTTER_VERSION=$(sed -n "s/^flutter \([0-9.]\+\).*/\1/p" .tool-versions)
      git clone -b $FLUTTER_VERSION --depth 1 https://github.com/flutter/flutter.git
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC/flutter $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $CRAFT_PART_INSTALL/usr/bin/dart
      $CRAFT_PART_INSTALL/usr/bin/flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''

  prompting-client:
    plugin: rust
    source: prompting-client
    override-build: |
      set -e
      mkdir -p $(dirname $CRAFT_PART_SRC)/protos
      cp $CRAFT_PROJECT_DIR/protos/* $(dirname $CRAFT_PART_SRC)/protos/
      craftctl default
    build-packages:
      - libssl-dev
      - pkg-config
    build-snaps:
      - protobuf

  prompting-client-ui:
    after: [flutter-git]
    source: .
    plugin: nil
    override-build: |
      set -e
      dart pub global activate melos
      dart pub global run melos clean
      dart pub global run melos bootstrap
      dart pub global run melos generate

      cd flutter_packages/prompting_client_ui
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
