name: apparmor-prompting
base: core22
version: '0.1'
summary: A simple apparmor prompting client
description: |
  An initial apparmor prompting client to support internal user testing
  and iteration on the UI.
grade: devel
confinement: strict

plugs:
  snap:
    interface: system-files
    read:
      - /snap

apps:
  apparmor-prompting:
    command: bin/aa-prompt-client
    extensions: [gnome]
    plugs:
      - desktop-launch
      - home
      - snap
      - snap-prompting-control

  security-center:
    command: bin/security-center/security_center
    extensions: [gnome]
    plugs:
      - snap-prompting-control

parts:
  flutter-git:
    plugin: nil
    source: .
    override-pull: |
      # necessary when reruns using the same container
      if [ -d "flutter" ]; then
        rm -rf "flutter"
      fi

      craftctl default
      FLUTTER_VERSION=$(sed -n "s/^flutter \([0-9.]\+\).*/\1/p" .tool-versions)
      git clone -b $FLUTTER_VERSION --depth 1 https://github.com/flutter/flutter.git
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC/flutter $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $CRAFT_PART_INSTALL/usr/bin/dart
      $CRAFT_PART_INSTALL/usr/bin/flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''

  client:
    plugin: rust
    source: aa-prompt-client

  apparmor-prompt:
    after: [flutter-git]
    source: flutter_packages/apparmor_prompt
    plugin: nil
    override-build: |
      set -e
      dart run build_runner build
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/apparmor-prompt/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/apparmor-prompt/

  security-center:
    after: [flutter-git]
    source: flutter_packages/security_center
    plugin: nil
    override-build: |
      set -e
      dart run build_runner build
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/security-center/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/security-center/
