name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Build testing snap
        id: snapcraft
        uses: snapcore/action-build@v1
        with:
          path: testing-snap

      - name: Setup snapd and test snap
        run: |
          sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
          sudo snap refresh snapd --channel=latest/edge/prompting
          sudo snap set system experimental.apparmor-prompting=true

      - name: Install dependencies
        run: | 
          sudo apt-get install protobuf-compiler

      - name: Check generated files are up to date
        working-directory: ./aa-prompt-client
        run: |
          cargo clean
          cargo build

          # Compare generated files with committed files
          if ! diff -r ./src/protos ./src/protos; then
            echo "Protobuf files are not up-to-date. Please regenerate and commit them."
            exit 1
          fi
          echo "Protobuf files are up-to-date."

      - name: Run tests
        working-directory: ./aa-prompt-client
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings
          cargo test
