name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Rustfmt formatting
        uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./aa-prompt-client

      - name: Clippy linting
        uses: giraffate/clippy-action@v1
        with:
          reporter: "github-pr-review"
          github_token: ${{ secrets.GITHUB_TOKEN }}
        workdir: ./aa-prompt-client

      - name: Setup snapd
        run: |
          sudo snap install snapd
          sudo snap install snapcraft --classic
          snapcraft
          sudo snap install ./aa-prompting-test_0.1_amd64.snap --dangerous
          sudo snap refresh snapd --channel=latest/edge/prompting
          sudo snap set system experimental.apparmor-prompting=true

      - name: Run tests
        working-directory: ./aa-prompt-client
        run: cargo test
